services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'brownCat'
      MYSQL_USER: 'userOne'
      MYSQL_PASSWORD: 'project01'
      MYSQL_ROOT_PASSWORD: 'project01'
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where data will be persisted
    volumes:
      - my-db:/var/lib/mysql

# Name of volume
volumes:
  my-db: